"""add colomns create_at and updated_at

Revision ID: a097734b6fb9
Revises: f96c2aaab5b4
Create Date: 2024-12-22 12:27:04.403991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a097734b6fb9"
down_revision: Union[str, None] = "f96c2aaab5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "likes",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "likes",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "medias",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "medias",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "tweets",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "tweets",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("tweets", "updated_at")
    op.drop_column("tweets", "created_at")
    op.drop_column("medias", "updated_at")
    op.drop_column("medias", "created_at")
    op.drop_column("likes", "updated_at")
    op.drop_column("likes", "created_at")
    # ### end Alembic commands ###
