"""edit name colomn file_link on file_name in table media

Revision ID: e47e0bb54cc8
Revises: 8ad34bc67884
Create Date: 2024-12-28 06:16:16.118343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e47e0bb54cc8"
down_revision: Union[str, None] = "8ad34bc67884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medias", sa.Column("file_name", sa.VARCHAR(length=300))
    )
    op.drop_column("medias", "file_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medias",
        sa.Column(
            "file_link", sa.VARCHAR(length=300), autoincrement=False))
    op.drop_column("medias", "file_name")
    # ### end Alembic commands ###
