"""edit type in colomn api_key in User table

Revision ID: 8ad34bc67884
Revises: a097734b6fb9
Create Date: 2024-12-23 13:45:48.686338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "8ad34bc67884"
down_revision: Union[str, None] = "a097734b6fb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "api_key",
        existing_type=postgresql.BYTEA(),
        type_=sqlalchemy_utils.StringEncryptedType(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "api_key",
        existing_type=sqlalchemy_utils.StringEncryptedType(),
        type_=postgresql.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
